
/*
 ========================================
 ||                                      ||
 ||            Relatórios                ||
 ||                                      ||
 ========================================
 */

-- VERIFICAR PASSAGEIROS INCLUSOS NO VOO N°121
CREATE OR REPLACE FUNCTION VERIFICAR_PASSAGEIROS_POR_VOO(_ID_VOO INT) 
RETURNS TABLE(NOME_PASSAGEIRO TEXT) AS $$
BEGIN
    RETURN QUERY 
    SELECT IR.NOME_PASSAGEIRO 
    FROM ITEM_RESERVA IR
    WHERE IR.ID_VOO = _ID_VOO;
END;
$$ LANGUAGE plpgsql;
-- MODO DE UTILIZACAO
SELECT VERIFICAR_PASSAGEIROS_POR_VOO(7);

-- VERIFICAR RESERVAS ASSOCIADAS AO PASSAGEIRO DE ID 122
CREATE OR REPLACE FUNCTION VERIFICAR_MINHAS_RESERVAS(_ID_USUARIO INT)
RETURNS TABLE(_ID_RESERVA INT, _DATA_RESERVA TIMESTAMP, _VALOR_TOTAL_RESERVA DECIMAL) AS $$
BEGIN
    RETURN QUERY
    SELECT ID_RESERVA, DATA_RESERVA, VALOR_TOTAL_RESERVA
    FROM RESERVA 
    WHERE ID_USUARIO = _ID_USUARIO;
END;
$$ LANGUAGE plpgsql;
-- MODO DE UTILIZAÇÃO
SELECT _ID_RESERVA, _DATA_RESERVA, _VALOR_TOTAL_RESERVA 
FROM VERIFICAR_MINHAS_RESERVAS(1);

-- VERIFICAR PASSAGENS POR RESERVA
CREATE OR REPLACE FUNCTION VERIFICAR_PASSAGENS_POR_RESERVA(_ID_RESERVA INT)
RETURNS TABLE(_ID_ITEM_RESERVA INT, _NOME_PASSAGEIRO TEXT, _ID_VOO INT) AS $$
BEGIN
    RETURN QUERY
    SELECT ID_ITEM_RESERVA, NOME_PASSAGEIRO, ID_VOO 
    FROM ITEM_RESERVA 
    WHERE ID_RESERVA = _ID_RESERVA;
END;
$$ LANGUAGE plpgsql;
-- MODO DE UTILIZAÇÃO
SELECT _ID_ITEM_RESERVA INT, _NOME_PASSAGEIRO TEXT, _ID_VOO INT FROM VERIFICAR_PASSAGENS_POR_RESERVA(1);


